export const page_notice_titles = {
  auth_required: '请先登录后台账号',
  auth_admin_required: '请先登录后台管理员账号',
  admin_required: '需要管理员权限',
  readonly_mode: '当前角色为只读模式',
  alerts_access_limited: '该页面仅对管理员和教师开放',
  dashboard_error: '仪表盘异常',
  health_center_error: '加载失败',
  device_registry_error: '设备管理异常',
  device_binding_error: '手环绑定管理异常',
  equipment_error: '器材管理异常',
  wristband_error: '手环管理异常',
  env_quality_error: '环境页面异常',
  user_management_error: '用户管理异常',
  alerts_error: '告警管理异常',
  training_archive_error: '训练档案加载失败',
  training_archive_aggregate_result: '训练会话已同步',
  training_archive_ai_reserved: 'AI 分析能力已预留',
  training_archive_ai_ready: 'AI 分析入口已接线',
  wristband_list_error: '手环列表加载失败',
  wristband_binding_error: '绑定维护失败'
} as const;

export const page_error_fallbacks = {
  alerts_ack_failed: '告警确认失败',
  alerts_batch_ack_failed: '批量确认失败',
  alerts_device_filter_load_failed: '设备筛选项加载失败',
  alerts_load_failed: '告警加载失败',
  dashboard_load_failed: '仪表盘加载失败',
  device_registry_create_failed: '创建设备失败',
  device_registry_delete_failed: '删除设备失败',
  device_registry_list_load_failed: '设备管理列表加载失败',
  device_registry_update_failed: '更新设备失败',
  device_binding_list_load_failed: '手环绑定列表加载失败',
  env_config_publish_failed: '环境配置下发失败',
  env_data_load_failed: '环境数据加载失败',
  env_device_list_load_failed: '环境节点加载失败',
  equipment_config_publish_failed: '器材配置下发失败',
  equipment_list_load_failed: '器材列表加载失败',
  equipment_telemetry_load_failed: '器材数据加载失败',
  ops_alert_batch_close_failed: '批量关闭运维告警失败',
  ops_alert_close_failed: '运维告警关闭失败',
  training_archive_aggregate_failed: '训练会话同步失败',
  training_archive_ai_failed: 'AI 分析请求失败',
  training_archive_load_failed: '训练档案加载失败',
  user_create_failed: '创建用户失败',
  user_delete_failed: '删除用户失败',
  user_list_load_failed: '用户列表加载失败',
  user_update_failed: '更新用户失败',
  wristband_bind_failed: '绑定手环失败',
  wristband_config_publish_failed: '手环配置下发失败',
  wristband_data_load_failed: '手环数据加载失败',
  wristband_device_list_load_failed: '手环设备列表加载失败',
  wristband_list_load_failed: '手环列表加载失败',
  wristband_unbind_failed: '解绑手环失败'
} as const;
