from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
import time

import yaml

from app.utils.topic_parser import ParsedTopic


DEFAULT_RULES_PATH = Path("/runtime/config/edge_processor/rules.yaml")
DEFAULT_TIME_SOURCE = "payload_ts"
VALID_TIME_SOURCES = {"payload_ts", "gateway_received_ts", "backend_received_at"}


@dataclass(slots=True, frozen=True)
class DeviceOfflineRule:
    """Configuration for generated device-offline status and alert events."""

    enabled: bool
    timeout_s: int
    level: str


@dataclass(slots=True, frozen=True)
class EmittedAlert:
    """Alert generated by a local edge rule."""

    gym_id: str
    device_type: str
    device_id: str
    code: str
    level: str
    value: float
    threshold: float
    observed_at_s: int
    message: str


@dataclass(slots=True)
class _WindowState:
    """State for rules that require a condition to hold for a time window."""

    started_at_s: int
    fired: bool


class RuleEngine:
    """Evaluate local edge alert rules against telemetry payloads."""

    def __init__(self, rules_path: Path = DEFAULT_RULES_PATH) -> None:
        """Create a rule engine.

        :param rules_path: YAML rules file to load and reload at runtime.
        """
        self._rules_path = Path(rules_path)
        self._alert_rules: dict[str, dict[str, Any]] = {}
        self._global: dict[str, Any] = {}
        self._window_state: dict[tuple[str, str, str, str], _WindowState] = {}

    def reload_rules(self) -> None:
        """Reload alert rules from disk and prune obsolete window state."""
        data = self._read_yaml(self._rules_path)
        raw_rules = data.get("alert_rules", {})
        if isinstance(raw_rules, dict):
            self._alert_rules = {
                str(rule_code): rule_config
                for rule_code, rule_config in raw_rules.items()
                if isinstance(rule_config, dict)
            }
        else:
            self._alert_rules = {}

        raw_global = data.get("global", {})
        self._global = raw_global if isinstance(raw_global, dict) else {}
        self._prune_window_state()

    def evaluate_telemetry(
        self,
        parsed_topic: ParsedTopic,
        payload: dict[str, Any],
        *,
        gateway_received_at_s: int | None = None,
    ) -> list[EmittedAlert]:
        """Evaluate telemetry payloads and return newly emitted alerts.

        :param parsed_topic: Parsed MQTT topic for the telemetry message.
        :param payload: Device telemetry payload.
        :param gateway_received_at_s: Optional gateway receipt time in Unix seconds.
        :return: Alerts whose rule window crossed its firing threshold.
        """
        if parsed_topic.action != "telemetry":
            return []

        observed_at_s = self._resolve_observed_at_s(payload, gateway_received_at_s)
        emitted: list[EmittedAlert] = []
        emitted.extend(self._evaluate_eq_overload(parsed_topic, payload, observed_at_s))
        emitted.extend(
            self._evaluate_env_threshold(
                parsed_topic,
                payload,
                observed_at_s,
                "CO2_HIGH",
                "co2_ppm",
                "threshold_ppm",
            )
        )
        emitted.extend(
            self._evaluate_env_threshold(
                parsed_topic,
                payload,
                observed_at_s,
                "PM25_HIGH",
                "pm2_5",
                "threshold_ugm3",
            )
        )
        emitted.extend(
            self._evaluate_env_threshold(
                parsed_topic,
                payload,
                observed_at_s,
                "TEMP_HIGH",
                "temperature",
                "threshold_c",
            )
        )
        emitted.extend(
            self._evaluate_env_threshold(
                parsed_topic,
                payload,
                observed_at_s,
                "CO2_CRITICAL",
                "co2_ppm",
                "threshold_ppm",
            )
        )
        return emitted

    def device_offline_rule(self) -> DeviceOfflineRule:
        """Return the current DEVICE_OFFLINE rule configuration."""
        config = self._alert_rules.get("DEVICE_OFFLINE", {})
        enabled = bool(config.get("enabled", False))
        timeout_s = max(1, int(_as_number(config.get("timeout_s"), 30.0)))
        level = str(config.get("level") or "warning")
        return DeviceOfflineRule(enabled=enabled, timeout_s=timeout_s, level=level)

    def check_interval_s(self) -> int:
        """Return the configured rule monitor interval in seconds."""
        return max(1, int(_as_number(self._global.get("check_interval_s"), 1.0)))

    def time_source(self) -> str:
        """Return the configured timestamp source used for rule windows."""
        raw = self._global.get("time_source")
        if isinstance(raw, str) and raw in VALID_TIME_SOURCES:
            return raw
        return DEFAULT_TIME_SOURCE

    def _evaluate_eq_overload(
        self,
        parsed_topic: ParsedTopic,
        payload: dict[str, Any],
        observed_at_s: int,
    ) -> list[EmittedAlert]:
        """Evaluate the equipment overload rule for one payload."""
        if parsed_topic.device_type != "equipment":
            return []

        config = self._alert_rules.get("EQ_OVERLOAD", {})
        if not bool(config.get("enabled", False)):
            self._clear_state("EQ_OVERLOAD", parsed_topic)
            return []

        power_w = _as_number(payload.get("power_w"))
        rated_power_w = _as_number(payload.get("rated_power_w"))
        ratio_threshold = _as_number(config.get("threshold_ratio"))
        if power_w is None or rated_power_w is None or ratio_threshold is None or rated_power_w <= 0:
            self._clear_state("EQ_OVERLOAD", parsed_topic)
            return []

        threshold = rated_power_w * ratio_threshold
        condition = power_w >= threshold
        return self._advance_window(
            parsed_topic=parsed_topic,
            rule_code="EQ_OVERLOAD",
            level=str(config.get("level") or "warning"),
            observed_at_s=observed_at_s,
            condition=condition,
            value=power_w,
            threshold=threshold,
            message=f"equipment overload: power_w={power_w:.2f}, threshold={threshold:.2f}",
            window_s=max(1, int(_as_number(config.get("window_s"), 1.0))),
        )

    def _evaluate_env_threshold(
        self,
        parsed_topic: ParsedTopic,
        payload: dict[str, Any],
        observed_at_s: int,
        rule_code: str,
        payload_field: str,
        threshold_field: str,
    ) -> list[EmittedAlert]:
        """Evaluate one environment threshold rule for one payload."""
        if parsed_topic.device_type != "env":
            return []

        config = self._alert_rules.get(rule_code, {})
        if not bool(config.get("enabled", False)):
            self._clear_state(rule_code, parsed_topic)
            return []

        value = _as_number(payload.get(payload_field))
        threshold = _as_number(config.get(threshold_field))
        if value is None or threshold is None:
            self._clear_state(rule_code, parsed_topic)
            return []

        return self._advance_window(
            parsed_topic=parsed_topic,
            rule_code=rule_code,
            level=str(config.get("level") or "warning"),
            observed_at_s=observed_at_s,
            condition=value >= threshold,
            value=value,
            threshold=threshold,
            message=f"{rule_code} triggered: {payload_field}={value:.2f}, threshold={threshold:.2f}",
            window_s=max(1, int(_as_number(config.get("window_s"), 1.0))),
        )

    def _advance_window(
        self,
        *,
        parsed_topic: ParsedTopic,
        rule_code: str,
        level: str,
        observed_at_s: int,
        condition: bool,
        value: float,
        threshold: float,
        message: str,
        window_s: int,
    ) -> list[EmittedAlert]:
        """Advance a rule window and emit once when the window completes."""
        key = (rule_code, parsed_topic.gym_id, parsed_topic.device_type, parsed_topic.device_id)

        if not condition:
            self._window_state.pop(key, None)
            return []

        state = self._window_state.get(key)
        if state is None:
            state = _WindowState(started_at_s=observed_at_s, fired=False)
            self._window_state[key] = state

        if state.fired:
            return []

        if observed_at_s - state.started_at_s < window_s:
            return []

        state.fired = True
        return [
            EmittedAlert(
                gym_id=parsed_topic.gym_id,
                device_type=parsed_topic.device_type,
                device_id=parsed_topic.device_id,
                code=rule_code,
                level=level,
                value=float(value),
                threshold=float(threshold),
                observed_at_s=observed_at_s,
                message=message,
            )
        ]

    def _prune_window_state(self) -> None:
        """Drop in-memory windows for rules that are no longer enabled."""
        enabled_rules = {
            rule_code
            for rule_code, config in self._alert_rules.items()
            if bool(config.get("enabled", False))
        }
        self._window_state = {
            key: value
            for key, value in self._window_state.items()
            if key[0] in enabled_rules
        }

    def _clear_state(self, rule_code: str, parsed_topic: ParsedTopic) -> None:
        """Clear a rule window for a device when its input becomes invalid."""
        key = (rule_code, parsed_topic.gym_id, parsed_topic.device_type, parsed_topic.device_id)
        self._window_state.pop(key, None)

    def _resolve_observed_at_s(
        self,
        payload: dict[str, Any],
        gateway_received_at_s: int | None,
    ) -> int:
        """Resolve the timestamp used for rule window calculations."""
        source = self.time_source()
        if source == "gateway_received_ts":
            return _resolve_gateway_received_at_s(payload, gateway_received_at_s)
        if source == "backend_received_at":
            return _resolve_backend_received_at_s(payload, gateway_received_at_s)
        return _resolve_payload_ts_s(payload, gateway_received_at_s)

    @staticmethod
    def _read_yaml(path: Path) -> dict[str, Any]:
        """Read a YAML mapping from disk, returning an empty mapping if missing."""
        if not path.exists():
            return {}
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _as_number(raw: Any, default: float | None = None) -> float | None:
    """Coerce numeric config and payload values to float."""
    if isinstance(raw, bool):
        return default
    if isinstance(raw, (int, float)):
        return float(raw)
    return default


def _to_unix_seconds(raw: Any) -> int:
    """Coerce a numeric timestamp to Unix seconds."""
    value = _as_number(raw)
    if value is None:
        return int(time.time())
    return int(value)


def _resolve_payload_ts_s(payload: dict[str, Any], gateway_received_at_s: int | None) -> int:
    """Resolve device payload time, falling back to gateway receipt time."""
    raw = payload.get("ts")
    if _as_number(raw) is None:
        return _resolve_gateway_received_at_s(payload, gateway_received_at_s)
    return _to_unix_seconds(raw)


def _resolve_gateway_received_at_s(payload: dict[str, Any], gateway_received_at_s: int | None) -> int:
    """Resolve gateway receipt time from callback context or enriched payload."""
    if gateway_received_at_s is not None:
        return int(gateway_received_at_s)
    raw = payload.get("gateway_received_ts")
    if _as_number(raw) is None:
        return int(time.time())
    return _to_unix_seconds(raw)


def _resolve_backend_received_at_s(payload: dict[str, Any], gateway_received_at_s: int | None) -> int:
    """Resolve backend receipt time, falling back to gateway receipt time."""
    raw = payload.get("backend_received_at")
    if isinstance(raw, str):
        try:
            return int(datetime.fromisoformat(raw.replace("Z", "+00:00")).timestamp())
        except ValueError:
            pass
    elif _as_number(raw) is not None:
        return _to_unix_seconds(raw)
    return _resolve_gateway_received_at_s(payload, gateway_received_at_s)
