services:
  mosquitto:
    build:
      context: ../../..
      dockerfile: gateway/deployment/mosquitto/Dockerfile
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - ./runtime/config:/runtime/config
      - ./runtime/secrets:/runtime/secrets
      - ./runtime/certs:/runtime/certs
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  influxdb:
    build:
      context: ../../..
      dockerfile: gateway/deployment/influxdb/Dockerfile
    ports:
      - "8181:8181"
    restart: unless-stopped
    volumes:
      - ./runtime/config:/runtime/config
      - influxdb_data:/var/lib/influxdb3

  edge_processor:
    build:
      context: ../../..
      dockerfile: gateway/deployment/edge_processor/Dockerfile
    depends_on:
      - mosquitto
      - influxdb
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./runtime/config:/runtime/config

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
