from __future__ import annotations

import json
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from aiomqtt import Client

from app.settings import MqttSettings


class SimulatorMqttPublisher:
    """Async MQTT publisher wrapper for simulator output streams."""

    def __init__(self, settings: MqttSettings, *, client_id_suffix: str | None = None) -> None:
        """Create a publisher that connects lazily through an async context.

        :param settings: MQTT broker settings used for the connection.
        :param client_id_suffix: Optional suffix used to keep publisher client
            IDs distinct across device groups.
        :return: None.
        """
        self._settings = settings
        self._client_id_suffix = client_id_suffix
        self._client_context: AsyncIterator[Client] | None = None
        self._client: Client | None = None

    async def __aenter__(self) -> "SimulatorMqttPublisher":
        """Open the MQTT connection.

        :return: Connected publisher instance.
        """
        self._client_context = _build_client_context(
            self._settings,
            client_id_suffix=self._client_id_suffix,
        )
        self._client = await self._client_context.__aenter__()
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        """Close the MQTT connection.

        :param exc_type: Exception type from the async context, if any.
        :param exc: Exception instance from the async context, if any.
        :param tb: Traceback from the async context, if any.
        :return: None.
        """
        if self._client_context is None:
            return
        await self._client_context.__aexit__(exc_type, exc, tb)
        self._client_context = None
        self._client = None

    async def publish_json(self, *, topic: str, payload: dict[str, object], retain: bool = False) -> None:
        """Publish one JSON MQTT message.

        :param topic: Destination MQTT topic.
        :param payload: JSON-compatible payload generated by the scenario
            engine.
        :param retain: Whether the broker should retain the message.
        :return: None.
        :raises RuntimeError: If called before the async context connects.
        """
        if self._client is None:
            raise RuntimeError("mqtt client is not connected")
        encoded_payload = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        await self._client.publish(topic, payload=encoded_payload, qos=self._settings.qos, retain=retain)


def _build_client_id(settings: MqttSettings, client_id_suffix: str | None) -> str:
    """Build a stable MQTT client ID for one simulator publisher.

    :param settings: MQTT settings containing the base client ID.
    :param client_id_suffix: Optional suffix for a publish group.
    :return: Base client ID or suffixed client ID.
    """
    if not client_id_suffix:
        return settings.client_id
    return f"{settings.client_id}-{client_id_suffix}"


@asynccontextmanager
async def _build_client_context(
    settings: MqttSettings,
    *,
    client_id_suffix: str | None = None,
) -> AsyncIterator[Client]:
    """Create an aiomqtt client context.

    :param settings: MQTT broker connection settings.
    :param client_id_suffix: Optional suffix for the MQTT client identifier.
    :return: Async iterator yielding a connected MQTT client.
    """
    async with Client(
        hostname=settings.host,
        port=settings.port,
        identifier=_build_client_id(settings, client_id_suffix),
        username=settings.username,
        password=settings.password,
        keepalive=settings.keepalive_s,
    ) as client:
        yield client
